### ISSUE TITLE
Maven javadoc build failes when using JDK 11

### ISSUE THREAD

**Issue by rumline** [castorm/kafka-connect-http#22]
**Describe the bug**
Uninstall JDK 1.8.  Install JDK 11.0.7.  Perform a "maven package" or "maven install".  Javadoc build fails.

**Found fix**
Add:
`<configuration>
    <source>8</source>
</configuration>`

To the `<artifactId>maven-javadoc-plugin</artifactId>` section of the pom.xml file.

Project now builds successfully using JDK 11.

**Plugin:**
Version 0.7.4

**Comment by castorm** [comment]
Thanks for reporting this @rumline .

This one is already fixed, but feel free to submit the PR yourself in the future if you take the time to fix it. Contributions are welcome.

Best regards.

**Comment by dingobar** [comment]
Unfortunately I am still facing this issue on JDK 11.0.11, which is the current default in Ubuntu 20.04. Using `<configuration> <source>11</source> </configuration>` fixed it, but I guess that breaks it for Java 8 users. Would it be possible to just take the major JDK version instead of the complete version? Not familiar with the syntax used so unfortunately I cannot create a PR just off the bat here :/
