### ISSUE TITLE
JIRA example with propertie file

### ISSUE THREAD

**Issue by tstuber** [castorm/kafka-connect-http#33]
**Describe the bug**
I tried to use the JIRA example with a standalone connect worker and a locally hosted JIRA. During the start-up, the templating seems to fails (`the following has evaluated to null or missing: ==> timestamp`)

```
[2020-07-07 17:36:46,617] INFO WorkerSourceTask{id=sample-search-issues.jira.http.source-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:214)
[2020-07-07 17:36:47,256] ERROR Error executing FreeMarker template (freemarker.runtime:60)
FreeMarker template error:
The following has evaluated to null or missing:
==> timestamp  [in template "a5a5f524-92d3-4366-8836-200eeaa80848" at line 1, column 17]

----
Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${timestamp?datetime.iso?string["yyyy...  [in template "a5a5f524-92d3-4366-8836-200eeaa80848" at line 1, column 15]
----

Java stack trace (for programmers):
----
freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
        at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
        at freemarker.core.EvalUtil.coerceModelToPlainText(EvalUtil.java:455)
        at freemarker.core.Expression.evalAndCoerceToPlainText(Expression.java:117)
        at freemarker.core.BuiltInsForMultipleTypes$dateBI._eval(BuiltInsForMultipleTypes.java:253)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.Dot._eval(Dot.java:41)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.BuiltInsForMultipleTypes$stringBI._eval(BuiltInsForMultipleTypes.java:765)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DynamicKeyName._eval(DynamicKeyName.java:61)
        at freemarker.core.Expression.eval(Expression.java:101)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
        at freemarker.core.Environment.visit(Environment.java:334)
        at freemarker.core.Environment.visit(Environment.java:340)
        at freemarker.core.Environment.process(Environment.java:313)
        at freemarker.template.Template.process(Template.java:383)
        at com.github.castorm.kafka.connect.http.request.template.freemarker.FreeMarkerTemplateFactory.apply(FreeMarkerTemplateFactory.java:55)
        at com.github.castorm.kafka.connect.http.request.template.freemarker.FreeMarkerTemplateFactory.lambda$create$0(FreeMarkerTemplateFactory.java:44)
        at com.github.castorm.kafka.connect.http.request.template.TemplateHttpRequestFactory.createRequest(TemplateHttpRequestFactory.java:64)
        at com.github.castorm.kafka.connect.http.HttpSourceTask.poll(HttpSourceTask.java:97)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:270)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:237)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2020-07-07 17:36:47,263] INFO WorkerSourceTask{id=sample-search-issues.jira.http.source-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask:424)
[2020-07-07 17:36:47,263] INFO WorkerSourceTask{id=sample-search-issues.jira.http.source-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask:441)
[2020-07-07 17:36:47,263] ERROR WorkerSourceTask{id=sample-search-issues.jira.http.source-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
FreeMarker template error:
The following has evaluated to null or missing:
==> timestamp  [in template "a5a5f524-92d3-4366-8836-200eeaa80848" at line 1, column 17]
```

**To Reproduce**
I used the provided [JIRA example (JSON)](https://github.com/castorm/kafka-connect-http/blob/master/examples/jira-issues-search.md) to derive the following property file:

```
name=sample-search-issues.jira.http.source
connector.class=com.github.castorm.kafka.connect.http.HttpSourceConnector
tasks.max=1
http.offset.initial="timestamp=2020-05-08T07:55:44Z"
http.request.url=http://localhost:8080/rest/api/2/search
http.request.headers="Authorization: Basic xyz, Accept: application/json, Accept-Encoding: *"
http.request.params="jql=updated>=${timestamp?datetime.iso?string['yyyy/MM/dd HH:mm']} ORDER BY updated ASC&maxResults=100"
http.response.list.pointer=/issues
http.response.record.key.pointer=/id
http.response.record.timestamp.pointer=/fields/updated
http.throttler.interval.millis=30000
http.throttler.catchup.interval.millis=1000
kafka.topic=jira
```

**Expected behavior**
"CDC-like" polling of JIRA API

**Kafka Connect:**
 - Version 2.5

**Plugin**
- castorm-kafka-connect-http-0.7.6

**Comment by castorm** [comment]
Hi tstuber,

Sorry for the late reply.

The template engine is complaining about the `timestamp` property being missing.

`timestamp` property is resolved for every item in the HTTP response via the json pointer: `/fields/updated`.

It would help to have a sample response from your JIRA API, would that be possible?

Thanks,
Best regards.

**Comment by tstuber** [comment]
Hi @castorm 

Thank for your answer. 

Here is an example of the response I get when querying the jira api directly (`curl localhost:8080/rest/api/2/search`):

```
{
    "expand": "schema,names",
    "startAt": 0,
    "maxResults": 50,
    "total": 1,
    "issues": [
        {
            "expand": "operations,versionedRepresentations,editmeta,changelog,renderedFields",
            "id": "10100",
            "self": "http://localhost:8080/rest/api/2/issue/10100",
            "key": "CICD-1",
            "fields": {
                "issuetype": {
                    "self": "http://localhost:8080/rest/api/2/issuetype/10002",
                    "id": "10002",
                    "description": "Created by Jira Software - do not edit or delete. Issue type for a user story.",
                    "iconUrl": "http://localhost:8080/images/icons/issuetypes/story.svg",
                    "name": "Story",
                    "subtask": false
                },
                "components": [],
                "timespent": null,
                "timeoriginalestimate": null,
                "description": null,
                "project": {
                    "self": "http://localhost:8080/rest/api/2/project/10100",
                    "id": "10100",
                    "key": "CICD",
                    "name": "CICD",
                    "projectTypeKey": "software",
                    "avatarUrls": {
                        "48x48": "http://localhost:8080/secure/projectavatar?avatarId=10324",
                        "24x24": "http://localhost:8080/secure/projectavatar?size=small&avatarId=10324",
                        "16x16": "http://localhost:8080/secure/projectavatar?size=xsmall&avatarId=10324",
                        "32x32": "http://localhost:8080/secure/projectavatar?size=medium&avatarId=10324"
                    }
                },
                "fixVersions": [],
                "aggregatetimespent": null,
                "resolution": null,
                "customfield_10104": null,
                "customfield_10105": "0|i00007:",
                "customfield_10106": null,
                "aggregatetimeestimate": null,
                "resolutiondate": null,
                "workratio": -1,
                "summary": "Create pipeline",
                "lastViewed": null,
                "watches": {
                    "self": "http://localhost:8080/rest/api/2/issue/CICD-1/watchers",
                    "watchCount": 1,
                    "isWatching": true
                },
                "creator": {
                    "self": "http://localhost:8080/rest/api/2/user?username=username",
                    "name": "username",
                    "key": "JIRAUSER10000",
                    "emailAddress": "username@mail.com",
                    "avatarUrls": {
                        "48x48": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=48",
                        "24x24": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=24",
                        "16x16": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=16",
                        "32x32": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=32"
                    },
                    "displayName": "username@mail.com",
                    "active": true,
                    "timeZone": "GMT"
                },
                "subtasks": [],
                "created": "2020-07-07T13:42:01.000+0000",
                "reporter": {
                    "self": "http://localhost:8080/rest/api/2/user?username=username",
                    "name": "username",
                    "key": "JIRAUSER10000",
                    "emailAddress": "username@mail.com",
                    "avatarUrls": {
                        "48x48": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=48",
                        "24x24": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=24",
                        "16x16": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=16",
                        "32x32": "https://www.gravatar.com/avatar/88d52f97a9ed6a976d49389c42de9e48?d=mm&s=32"
                    },
                    "displayName": "username@mail.com",
                    "active": true,
                    "timeZone": "GMT"
                },
                "customfield_10000": "{summaryBean=com.atlassian.jira.plugin.devstatus.rest.SummaryBean@48105399[summary={pullrequest=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@456d7974[overall=PullRequestOverallBean{stateCount=0, state='OPEN', details=PullRequestOverallDetails{openCount=0, mergedCount=0, declinedCount=0}},byInstanceType={}], build=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@6db704d6[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BuildOverallBean@433f76cd[failedBuildCount=0,successfulBuildCount=0,unknownBuildCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], review=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@2264adc6[overall=com.atlassian.jira.plugin.devstatus.summary.beans.ReviewsOverallBean@d03a677[stateCount=0,state=<null>,dueDate=<null>,overDue=false,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], deployment-environment=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@584792b5[overall=com.atlassian.jira.plugin.devstatus.summary.beans.DeploymentOverallBean@60760e6e[topEnvironments=[],showProjects=false,successfulCount=0,count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], repository=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@677b853b[overall=com.atlassian.jira.plugin.devstatus.summary.beans.CommitOverallBean@77dbb7bd[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}], branch=com.atlassian.jira.plugin.devstatus.rest.SummaryItemBean@136d51c9[overall=com.atlassian.jira.plugin.devstatus.summary.beans.BranchOverallBean@433828b4[count=0,lastUpdated=<null>,lastUpdatedTimestamp=<null>],byInstanceType={}]},errors=[],configErrors=[]], devSummaryJson={\"cachedValue\":{\"errors\":[],\"configErrors\":[],\"summary\":{\"pullrequest\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":\"OPEN\",\"details\":{\"openCount\":0,\"mergedCount\":0,\"declinedCount\":0,\"total\":0},\"open\":true},\"byInstanceType\":{}},\"build\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"failedBuildCount\":0,\"successfulBuildCount\":0,\"unknownBuildCount\":0},\"byInstanceType\":{}},\"review\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"stateCount\":0,\"state\":null,\"dueDate\":null,\"overDue\":false,\"completed\":false},\"byInstanceType\":{}},\"deployment-environment\":{\"overall\":{\"count\":0,\"lastUpdated\":null,\"topEnvironments\":[],\"showProjects\":false,\"successfulCount\":0},\"byInstanceType\":{}},\"repository\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}},\"branch\":{\"overall\":{\"count\":0,\"lastUpdated\":null},\"byInstanceType\":{}}}},\"isStale\":false}}",
                "aggregateprogress": {
                    "progress": 0,
                    "total": 0
                },
                "priority": {
                    "self": "http://localhost:8080/rest/api/2/priority/3",
                    "iconUrl": "http://localhost:8080/images/icons/priorities/medium.svg",
                    "name": "Medium",
                    "id": "3"
                },
                "customfield_10100": null,
                "labels": [],
                "environment": null,
                "timeestimate": null,
                "aggregatetimeoriginalestimate": null,
                "versions": [],
                "duedate": null,
                "progress": {
                    "progress": 0,
                    "total": 0
                },
                "issuelinks": [],
                "votes": {
                    "self": "http://localhost:8080/rest/api/2/issue/CICD-1/votes",
                    "votes": 0,
                    "hasVoted": false
                },
                "assignee": null,
                "updated": "2020-07-07T13:42:01.000+0000",
                "status": {
                    "self": "http://localhost:8080/rest/api/2/status/10000",
                    "description": "",
                    "iconUrl": "http://localhost:8080/",
                    "name": "To Do",
                    "id": "10000",
                    "statusCategory": {
                        "self": "http://localhost:8080/rest/api/2/statuscategory/2",
                        "id": 2,
                        "key": "new",
                        "colorName": "blue-gray",
                        "name": "To Do"
                    }
                }
            }
        }
    ]
}
```

Actually I believe the the used pointer `http.response.record.timestamp.pointer=/fields/updated` should be correct...

Cheers
Thomas

**Comment by gonits** [comment]
Hi @castorm I am also getting the same error. timestamp not resolved when trying to hit jira api.

**Comment by gonits** [comment]
It got resolved, after I override this method-> start() for setting offset properties (key and timestamp). Seems to be working now for CDC data.
the code i changed: 
offset = Offset.of(!restoredOffset.isEmpty() ? restoredOffset : config.getInitialOffset(),"test",Instant.parse(config.getInitialOffset().get("timestamp")));
